// This code conforms with the UFC specification version 1.6.0
// and was automatically generated by FFC version 1.6.0.
// 
// This code was generated with the following parameters:
// 
//   convert_exceptions_to_warnings: False
//   cpp_optimize:                   True
//   cpp_optimize_flags:             '-O2'
//   epsilon:                        1e-14
//   error_control:                  False
//   form_postfix:                   False
//   format:                         'ufc'
//   name:                           'ffc'
//   no-evaluate_basis_derivatives:  True
//   optimize:                       False
//   precision:                      15
//   quadrature_degree:              -1
//   quadrature_rule:                'auto'
//   representation:                 'auto'
//   restrict_keyword:               ''
//   split:                          False

#ifndef __FFC_FORM_18F96071AF3B89AB94A8A484EFBD06F319830499_H
#define __FFC_FORM_18F96071AF3B89AB94A8A484EFBD06F319830499_H

#include <cmath>
#include <stdexcept>
#include <fstream>
#include <ufc.h>

/// This class defines the interface for a finite element.

class ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_finite_element_0: public ufc::finite_element
{
public:

  /// Constructor
  ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_finite_element_0() : ufc::finite_element()
  {
    // Do nothing
  }

  /// Destructor
  virtual ~ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_finite_element_0()
  {
    // Do nothing
  }

  /// Return a string identifying the finite element
  virtual const char* signature() const
  {
    return "FiniteElement('Lagrange', Domain(Cell('triangle', 2)), 2, None)";
  }

  /// Return the cell shape
  virtual ufc::shape cell_shape() const
  {
    return ufc::triangle;
  }

  /// Return the topological dimension of the cell shape
  virtual std::size_t topological_dimension() const
  {
    return 2;
  }

  /// Return the geometric dimension of the cell shape
  virtual std::size_t geometric_dimension() const
  {
    return 2;
  }

  /// Return the dimension of the finite element function space
  virtual std::size_t space_dimension() const
  {
    return 6;
  }

  /// Return the rank of the value space
  virtual std::size_t value_rank() const
  {
    return 0;
  }

  /// Return the dimension of the value space for axis i
  virtual std::size_t value_dimension(std::size_t i) const
  {
    return 1;
  }

  /// Evaluate basis function i at given point x in cell (actual implementation)
  static void _evaluate_basis(std::size_t i,
                              double* values,
                              const double* x,
                              const double* vertex_coordinates,
                              int cell_orientation)
  {
    // Compute Jacobian
    double J[4];
    compute_jacobian_triangle_2d(J, vertex_coordinates);
    
    // Compute Jacobian inverse and determinant
    double K[4];
    double detJ;
    compute_jacobian_inverse_triangle_2d(K, detJ, J);
    
    
    // Compute constants
    const double C0 = vertex_coordinates[2] + vertex_coordinates[4];
    const double C1 = vertex_coordinates[3] + vertex_coordinates[5];
    
    // Get coordinates and map to the reference (FIAT) element
    double X = (J[1]*(C1 - 2.0*x[1]) + J[3]*(2.0*x[0] - C0)) / detJ;
    double Y = (J[0]*(2.0*x[1] - C1) + J[2]*(C0 - 2.0*x[0])) / detJ;
    
    // Reset values
    *values = 0.0;
    switch (i)
    {
    case 0:
      {
        
      // Array of basisvalues
      double basisvalues[6] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
      
      // Declare helper variables
      double tmp0 = (1.0 + Y + 2.0*X)/2.0;
      double tmp1 = (1.0 - Y)/2.0;
      double tmp2 = tmp1*tmp1;
      
      // Compute basisvalues
      basisvalues[0] = 1.0;
      basisvalues[1] = tmp0;
      basisvalues[3] = basisvalues[1]*1.5*tmp0 - basisvalues[0]*0.5*tmp2;
      basisvalues[2] = basisvalues[0]*(0.5 + 1.5*Y);
      basisvalues[4] = basisvalues[1]*(1.5 + 2.5*Y);
      basisvalues[5] = basisvalues[2]*(0.111111111111111 + Y*1.66666666666667) - basisvalues[0]*0.555555555555556;
      basisvalues[0] *= std::sqrt(0.5);
      basisvalues[2] *= std::sqrt(1.0);
      basisvalues[5] *= std::sqrt(1.5);
      basisvalues[1] *= std::sqrt(3.0);
      basisvalues[4] *= std::sqrt(4.5);
      basisvalues[3] *= std::sqrt(7.5);
      
      // Table(s) of coefficients
      static const double coefficients0[6] = \
      {0.0, -0.173205080756888, -0.1, 0.121716123890037, 0.0942809041582063, 0.0544331053951817};
      
      // Compute value(s)
      for (unsigned int r = 0; r < 6; r++)
      {
        *values += coefficients0[r]*basisvalues[r];
      } // end loop over 'r'
        break;
      }
    case 1:
      {
        
      // Array of basisvalues
      double basisvalues[6] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
      
      // Declare helper variables
      double tmp0 = (1.0 + Y + 2.0*X)/2.0;
      double tmp1 = (1.0 - Y)/2.0;
      double tmp2 = tmp1*tmp1;
      
      // Compute basisvalues
      basisvalues[0] = 1.0;
      basisvalues[1] = tmp0;
      basisvalues[3] = basisvalues[1]*1.5*tmp0 - basisvalues[0]*0.5*tmp2;
      basisvalues[2] = basisvalues[0]*(0.5 + 1.5*Y);
      basisvalues[4] = basisvalues[1]*(1.5 + 2.5*Y);
      basisvalues[5] = basisvalues[2]*(0.111111111111111 + Y*1.66666666666667) - basisvalues[0]*0.555555555555556;
      basisvalues[0] *= std::sqrt(0.5);
      basisvalues[2] *= std::sqrt(1.0);
      basisvalues[5] *= std::sqrt(1.5);
      basisvalues[1] *= std::sqrt(3.0);
      basisvalues[4] *= std::sqrt(4.5);
      basisvalues[3] *= std::sqrt(7.5);
      
      // Table(s) of coefficients
      static const double coefficients0[6] = \
      {0.0, 0.173205080756888, -0.1, 0.121716123890037, -0.0942809041582064, 0.0544331053951818};
      
      // Compute value(s)
      for (unsigned int r = 0; r < 6; r++)
      {
        *values += coefficients0[r]*basisvalues[r];
      } // end loop over 'r'
        break;
      }
    case 2:
      {
        
      // Array of basisvalues
      double basisvalues[6] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
      
      // Declare helper variables
      double tmp0 = (1.0 + Y + 2.0*X)/2.0;
      double tmp1 = (1.0 - Y)/2.0;
      double tmp2 = tmp1*tmp1;
      
      // Compute basisvalues
      basisvalues[0] = 1.0;
      basisvalues[1] = tmp0;
      basisvalues[3] = basisvalues[1]*1.5*tmp0 - basisvalues[0]*0.5*tmp2;
      basisvalues[2] = basisvalues[0]*(0.5 + 1.5*Y);
      basisvalues[4] = basisvalues[1]*(1.5 + 2.5*Y);
      basisvalues[5] = basisvalues[2]*(0.111111111111111 + Y*1.66666666666667) - basisvalues[0]*0.555555555555556;
      basisvalues[0] *= std::sqrt(0.5);
      basisvalues[2] *= std::sqrt(1.0);
      basisvalues[5] *= std::sqrt(1.5);
      basisvalues[1] *= std::sqrt(3.0);
      basisvalues[4] *= std::sqrt(4.5);
      basisvalues[3] *= std::sqrt(7.5);
      
      // Table(s) of coefficients
      static const double coefficients0[6] = \
      {0.0, 0.0, 0.2, 0.0, 0.0, 0.163299316185545};
      
      // Compute value(s)
      for (unsigned int r = 0; r < 6; r++)
      {
        *values += coefficients0[r]*basisvalues[r];
      } // end loop over 'r'
        break;
      }
    case 3:
      {
        
      // Array of basisvalues
      double basisvalues[6] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
      
      // Declare helper variables
      double tmp0 = (1.0 + Y + 2.0*X)/2.0;
      double tmp1 = (1.0 - Y)/2.0;
      double tmp2 = tmp1*tmp1;
      
      // Compute basisvalues
      basisvalues[0] = 1.0;
      basisvalues[1] = tmp0;
      basisvalues[3] = basisvalues[1]*1.5*tmp0 - basisvalues[0]*0.5*tmp2;
      basisvalues[2] = basisvalues[0]*(0.5 + 1.5*Y);
      basisvalues[4] = basisvalues[1]*(1.5 + 2.5*Y);
      basisvalues[5] = basisvalues[2]*(0.111111111111111 + Y*1.66666666666667) - basisvalues[0]*0.555555555555556;
      basisvalues[0] *= std::sqrt(0.5);
      basisvalues[2] *= std::sqrt(1.0);
      basisvalues[5] *= std::sqrt(1.5);
      basisvalues[1] *= std::sqrt(3.0);
      basisvalues[4] *= std::sqrt(4.5);
      basisvalues[3] *= std::sqrt(7.5);
      
      // Table(s) of coefficients
      static const double coefficients0[6] = \
      {0.471404520791032, 0.23094010767585, 0.133333333333333, 0.0, 0.188561808316413, -0.163299316185545};
      
      // Compute value(s)
      for (unsigned int r = 0; r < 6; r++)
      {
        *values += coefficients0[r]*basisvalues[r];
      } // end loop over 'r'
        break;
      }
    case 4:
      {
        
      // Array of basisvalues
      double basisvalues[6] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
      
      // Declare helper variables
      double tmp0 = (1.0 + Y + 2.0*X)/2.0;
      double tmp1 = (1.0 - Y)/2.0;
      double tmp2 = tmp1*tmp1;
      
      // Compute basisvalues
      basisvalues[0] = 1.0;
      basisvalues[1] = tmp0;
      basisvalues[3] = basisvalues[1]*1.5*tmp0 - basisvalues[0]*0.5*tmp2;
      basisvalues[2] = basisvalues[0]*(0.5 + 1.5*Y);
      basisvalues[4] = basisvalues[1]*(1.5 + 2.5*Y);
      basisvalues[5] = basisvalues[2]*(0.111111111111111 + Y*1.66666666666667) - basisvalues[0]*0.555555555555556;
      basisvalues[0] *= std::sqrt(0.5);
      basisvalues[2] *= std::sqrt(1.0);
      basisvalues[5] *= std::sqrt(1.5);
      basisvalues[1] *= std::sqrt(3.0);
      basisvalues[4] *= std::sqrt(4.5);
      basisvalues[3] *= std::sqrt(7.5);
      
      // Table(s) of coefficients
      static const double coefficients0[6] = \
      {0.471404520791032, -0.23094010767585, 0.133333333333333, 0.0, -0.188561808316413, -0.163299316185545};
      
      // Compute value(s)
      for (unsigned int r = 0; r < 6; r++)
      {
        *values += coefficients0[r]*basisvalues[r];
      } // end loop over 'r'
        break;
      }
    case 5:
      {
        
      // Array of basisvalues
      double basisvalues[6] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
      
      // Declare helper variables
      double tmp0 = (1.0 + Y + 2.0*X)/2.0;
      double tmp1 = (1.0 - Y)/2.0;
      double tmp2 = tmp1*tmp1;
      
      // Compute basisvalues
      basisvalues[0] = 1.0;
      basisvalues[1] = tmp0;
      basisvalues[3] = basisvalues[1]*1.5*tmp0 - basisvalues[0]*0.5*tmp2;
      basisvalues[2] = basisvalues[0]*(0.5 + 1.5*Y);
      basisvalues[4] = basisvalues[1]*(1.5 + 2.5*Y);
      basisvalues[5] = basisvalues[2]*(0.111111111111111 + Y*1.66666666666667) - basisvalues[0]*0.555555555555556;
      basisvalues[0] *= std::sqrt(0.5);
      basisvalues[2] *= std::sqrt(1.0);
      basisvalues[5] *= std::sqrt(1.5);
      basisvalues[1] *= std::sqrt(3.0);
      basisvalues[4] *= std::sqrt(4.5);
      basisvalues[3] *= std::sqrt(7.5);
      
      // Table(s) of coefficients
      static const double coefficients0[6] = \
      {0.471404520791032, 0.0, -0.266666666666667, -0.243432247780074, 0.0, 0.0544331053951817};
      
      // Compute value(s)
      for (unsigned int r = 0; r < 6; r++)
      {
        *values += coefficients0[r]*basisvalues[r];
      } // end loop over 'r'
        break;
      }
    }
    
  }

  /// Evaluate basis function i at given point x in cell (non-static member function)
  virtual void evaluate_basis(std::size_t i,
                              double* values,
                              const double* x,
                              const double* vertex_coordinates,
                              int cell_orientation) const
  {
    _evaluate_basis(i, values, x, vertex_coordinates, cell_orientation);
  }

  /// Evaluate all basis functions at given point x in cell (actual implementation)
  static void _evaluate_basis_all(double* values,
                                  const double* x,
                                  const double* vertex_coordinates,
                                  int cell_orientation)
  {
    // Helper variable to hold values of a single dof.
    double dof_values = 0.0;
    
    // Loop dofs and call evaluate_basis
    for (unsigned int r = 0; r < 6; r++)
    {
      _evaluate_basis(r, &dof_values, x, vertex_coordinates, cell_orientation);
      values[r] = dof_values;
    } // end loop over 'r'
  }

  /// Evaluate all basis functions at given point x in cell (non-static member function)
  virtual void evaluate_basis_all(double* values,
                                  const double* x,
                                  const double* vertex_coordinates,
                                  int cell_orientation) const
  {
    _evaluate_basis_all(values, x, vertex_coordinates, cell_orientation);
  }

  /// Evaluate order n derivatives of basis function i at given point x in cell (actual implementation)
  static void _evaluate_basis_derivatives(std::size_t i,
                                          std::size_t n,
                                          double* values,
                                          const double* x,
                                          const double* vertex_coordinates,
                                          int cell_orientation)
  {
throw std::runtime_error("// Function evaluate_basis_derivatives not generated (compiled with -fno-evaluate_basis_derivatives)");
  }

  /// Evaluate order n derivatives of basis function i at given point x in cell (non-static member function)
  virtual void evaluate_basis_derivatives(std::size_t i,
                                          std::size_t n,
                                          double* values,
                                          const double* x,
                                          const double* vertex_coordinates,
                                          int cell_orientation) const
  {
    _evaluate_basis_derivatives(i, n, values, x, vertex_coordinates, cell_orientation);
  }

  /// Evaluate order n derivatives of all basis functions at given point x in cell (actual implementation)
  static void _evaluate_basis_derivatives_all(std::size_t n,
                                              double* values,
                                              const double* x,
                                              const double* vertex_coordinates,
                                              int cell_orientation)
  {
    // Call evaluate_basis_all if order of derivatives is equal to zero.
    if (n == 0)
    {
      _evaluate_basis_all(values, x, vertex_coordinates, cell_orientation);
      return ;
    }
    
    // Compute number of derivatives.
    unsigned int num_derivatives = 1;
    for (unsigned int r = 0; r < n; r++)
    {
      num_derivatives *= 2;
    } // end loop over 'r'
    
    // Set values equal to zero.
    for (unsigned int r = 0; r < 6; r++)
    {
      for (unsigned int s = 0; s < num_derivatives; s++)
      {
        values[r*num_derivatives + s] = 0.0;
      } // end loop over 's'
    } // end loop over 'r'
    
    // If order of derivatives is greater than the maximum polynomial degree, return zeros.
    if (n > 2)
    {
      return ;
    }
    
    // Helper variable to hold values of a single dof.
    double dof_values[4];
    for (unsigned int r = 0; r < 4; r++)
    {
      dof_values[r] = 0.0;
    } // end loop over 'r'
    
    // Loop dofs and call evaluate_basis_derivatives.
    for (unsigned int r = 0; r < 6; r++)
    {
      _evaluate_basis_derivatives(r, n, dof_values, x, vertex_coordinates, cell_orientation);
      for (unsigned int s = 0; s < num_derivatives; s++)
      {
        values[r*num_derivatives + s] = dof_values[s];
      } // end loop over 's'
    } // end loop over 'r'
  }

  /// Evaluate order n derivatives of all basis functions at given point x in cell (non-static member function)
  virtual void evaluate_basis_derivatives_all(std::size_t n,
                                              double* values,
                                              const double* x,
                                              const double* vertex_coordinates,
                                              int cell_orientation) const
  {
    _evaluate_basis_derivatives_all(n, values, x, vertex_coordinates, cell_orientation);
  }

  /// Evaluate linear functional for dof i on the function f
  virtual double evaluate_dof(std::size_t i,
                              const ufc::function& f,
                              const double* vertex_coordinates,
                              int cell_orientation,
                              const ufc::cell& c) const
  {
    // Declare variables for result of evaluation
    double vals[1];
    
    // Declare variable for physical coordinates
    double y[2];
    switch (i)
    {
    case 0:
      {
        y[0] = vertex_coordinates[0];
      y[1] = vertex_coordinates[1];
      f.evaluate(vals, y, c);
      return vals[0];
        break;
      }
    case 1:
      {
        y[0] = vertex_coordinates[2];
      y[1] = vertex_coordinates[3];
      f.evaluate(vals, y, c);
      return vals[0];
        break;
      }
    case 2:
      {
        y[0] = vertex_coordinates[4];
      y[1] = vertex_coordinates[5];
      f.evaluate(vals, y, c);
      return vals[0];
        break;
      }
    case 3:
      {
        y[0] = 0.5*vertex_coordinates[2] + 0.5*vertex_coordinates[4];
      y[1] = 0.5*vertex_coordinates[3] + 0.5*vertex_coordinates[5];
      f.evaluate(vals, y, c);
      return vals[0];
        break;
      }
    case 4:
      {
        y[0] = 0.5*vertex_coordinates[0] + 0.5*vertex_coordinates[4];
      y[1] = 0.5*vertex_coordinates[1] + 0.5*vertex_coordinates[5];
      f.evaluate(vals, y, c);
      return vals[0];
        break;
      }
    case 5:
      {
        y[0] = 0.5*vertex_coordinates[0] + 0.5*vertex_coordinates[2];
      y[1] = 0.5*vertex_coordinates[1] + 0.5*vertex_coordinates[3];
      f.evaluate(vals, y, c);
      return vals[0];
        break;
      }
    }
    
    return 0.0;
  }

  /// Evaluate linear functionals for all dofs on the function f
  virtual void evaluate_dofs(double* values,
                             const ufc::function& f,
                             const double* vertex_coordinates,
                             int cell_orientation,
                             const ufc::cell& c) const
  {
    // Declare variables for result of evaluation
    double vals[1];
    
    // Declare variable for physical coordinates
    double y[2];
    y[0] = vertex_coordinates[0];
    y[1] = vertex_coordinates[1];
    f.evaluate(vals, y, c);
    values[0] = vals[0];
    y[0] = vertex_coordinates[2];
    y[1] = vertex_coordinates[3];
    f.evaluate(vals, y, c);
    values[1] = vals[0];
    y[0] = vertex_coordinates[4];
    y[1] = vertex_coordinates[5];
    f.evaluate(vals, y, c);
    values[2] = vals[0];
    y[0] = 0.5*vertex_coordinates[2] + 0.5*vertex_coordinates[4];
    y[1] = 0.5*vertex_coordinates[3] + 0.5*vertex_coordinates[5];
    f.evaluate(vals, y, c);
    values[3] = vals[0];
    y[0] = 0.5*vertex_coordinates[0] + 0.5*vertex_coordinates[4];
    y[1] = 0.5*vertex_coordinates[1] + 0.5*vertex_coordinates[5];
    f.evaluate(vals, y, c);
    values[4] = vals[0];
    y[0] = 0.5*vertex_coordinates[0] + 0.5*vertex_coordinates[2];
    y[1] = 0.5*vertex_coordinates[1] + 0.5*vertex_coordinates[3];
    f.evaluate(vals, y, c);
    values[5] = vals[0];
  }

  /// Interpolate vertex values from dof values
  virtual void interpolate_vertex_values(double* vertex_values,
                                         const double* dof_values,
                                         const double* vertex_coordinates,
                                         int cell_orientation,
                                         const ufc::cell& c) const
  {
    // Evaluate function and change variables
    vertex_values[0] = dof_values[0];
    vertex_values[1] = dof_values[1];
    vertex_values[2] = dof_values[2];
  }

  /// Map coordinate xhat from reference cell to coordinate x in cell
  virtual void map_from_reference_cell(double* x,
                                       const double* xhat,
                                       const ufc::cell& c) const
  {
    throw std::runtime_error("map_from_reference_cell not yet implemented.");
  }

  /// Map from coordinate x in cell to coordinate xhat in reference cell
  virtual void map_to_reference_cell(double* xhat,
                                     const double* x,
                                     const ufc::cell& c) const
  {
    throw std::runtime_error("map_to_reference_cell not yet implemented.");
  }

  /// Return the number of sub elements (for a mixed element)
  virtual std::size_t num_sub_elements() const
  {
    return 0;
  }

  /// Create a new finite element for sub element i (for a mixed element)
  virtual ufc::finite_element* create_sub_element(std::size_t i) const
  {
    return 0;
  }

  /// Create a new class instance
  virtual ufc::finite_element* create() const
  {
    return new ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_finite_element_0();
  }

};

/// This class defines the interface for a local-to-global mapping of
/// degrees of freedom (dofs).

class ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_dofmap_0: public ufc::dofmap
{
public:

  /// Constructor
  ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_dofmap_0() : ufc::dofmap()
  {
    // Do nothing
  }

  /// Destructor
  virtual ~ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_dofmap_0()
  {
    // Do nothing
  }

  /// Return a string identifying the dofmap
  virtual const char* signature() const
  {
    return "FFC dofmap for FiniteElement('Lagrange', Domain(Cell('triangle', 2)), 2, None)";
  }

  /// Return true iff mesh entities of topological dimension d are needed
  virtual bool needs_mesh_entities(std::size_t d) const
  {
    switch (d)
    {
    case 0:
      {
        return true;
        break;
      }
    case 1:
      {
        return true;
        break;
      }
    case 2:
      {
        return false;
        break;
      }
    }
    
    return false;
  }

  /// Return the topological dimension of the associated cell shape
  virtual std::size_t topological_dimension() const
  {
    return 2;
  }

  /// Return the geometric dimension of the associated cell shape
  virtual std::size_t geometric_dimension() const
  {
    return 2;
  }

  /// Return the dimension of the global finite element function space
  virtual std::size_t global_dimension(const std::vector<std::size_t>&
                                       num_global_entities) const
  {
    return num_global_entities[0] + num_global_entities[1];
  }

  /// Return the dimension of the local finite element function space for a cell
  virtual std::size_t num_element_dofs() const
  {
    return 6;
  }

  /// Return the number of dofs on each cell facet
  virtual std::size_t num_facet_dofs() const
  {
    return 3;
  }

  /// Return the number of dofs associated with each cell entity of dimension d
  virtual std::size_t num_entity_dofs(std::size_t d) const
  {
    switch (d)
    {
    case 0:
      {
        return 1;
        break;
      }
    case 1:
      {
        return 1;
        break;
      }
    case 2:
      {
        return 0;
        break;
      }
    }
    
    return 0;
  }

  /// Tabulate the local-to-global mapping of dofs on a cell
  virtual void tabulate_dofs(std::size_t* dofs,
                             const std::vector<std::size_t>& num_global_entities,
                             const ufc::cell& c) const
  {
    unsigned int offset = 0;
    dofs[0] = offset + c.entity_indices[0][0];
    dofs[1] = offset + c.entity_indices[0][1];
    dofs[2] = offset + c.entity_indices[0][2];
    offset += num_global_entities[0];
    dofs[3] = offset + c.entity_indices[1][0];
    dofs[4] = offset + c.entity_indices[1][1];
    dofs[5] = offset + c.entity_indices[1][2];
    offset += num_global_entities[1];
  }

  /// Tabulate the local-to-local mapping from facet dofs to cell dofs
  virtual void tabulate_facet_dofs(std::size_t* dofs,
                                   std::size_t facet) const
  {
    switch (facet)
    {
    case 0:
      {
        dofs[0] = 1;
      dofs[1] = 2;
      dofs[2] = 3;
        break;
      }
    case 1:
      {
        dofs[0] = 0;
      dofs[1] = 2;
      dofs[2] = 4;
        break;
      }
    case 2:
      {
        dofs[0] = 0;
      dofs[1] = 1;
      dofs[2] = 5;
        break;
      }
    }
    
  }

  /// Tabulate the local-to-local mapping of dofs on entity (d, i)
  virtual void tabulate_entity_dofs(std::size_t* dofs,
                                    std::size_t d, std::size_t i) const
  {
    if (d > 2)
    {
    throw std::runtime_error("d is larger than dimension (2)");
    }
    
    switch (d)
    {
    case 0:
      {
        if (i > 2)
      {
      throw std::runtime_error("i is larger than number of entities (2)");
      }
      
      switch (i)
      {
      case 0:
        {
          dofs[0] = 0;
          break;
        }
      case 1:
        {
          dofs[0] = 1;
          break;
        }
      case 2:
        {
          dofs[0] = 2;
          break;
        }
      }
      
        break;
      }
    case 1:
      {
        if (i > 2)
      {
      throw std::runtime_error("i is larger than number of entities (2)");
      }
      
      switch (i)
      {
      case 0:
        {
          dofs[0] = 3;
          break;
        }
      case 1:
        {
          dofs[0] = 4;
          break;
        }
      case 2:
        {
          dofs[0] = 5;
          break;
        }
      }
      
        break;
      }
    case 2:
      {
        
        break;
      }
    }
    
  }

  /// Tabulate the coordinates of all dofs on a cell
  virtual void tabulate_coordinates(double* dof_coordinates,
                                    const double* vertex_coordinates) const
  {
    dof_coordinates[0] = vertex_coordinates[0];
    dof_coordinates[1] = vertex_coordinates[1];
    dof_coordinates[2] = vertex_coordinates[2];
    dof_coordinates[3] = vertex_coordinates[3];
    dof_coordinates[4] = vertex_coordinates[4];
    dof_coordinates[5] = vertex_coordinates[5];
    dof_coordinates[6] = 0.5*vertex_coordinates[2] + 0.5*vertex_coordinates[4];
    dof_coordinates[7] = 0.5*vertex_coordinates[3] + 0.5*vertex_coordinates[5];
    dof_coordinates[8] = 0.5*vertex_coordinates[0] + 0.5*vertex_coordinates[4];
    dof_coordinates[9] = 0.5*vertex_coordinates[1] + 0.5*vertex_coordinates[5];
    dof_coordinates[10] = 0.5*vertex_coordinates[0] + 0.5*vertex_coordinates[2];
    dof_coordinates[11] = 0.5*vertex_coordinates[1] + 0.5*vertex_coordinates[3];
  }

  /// Return the number of sub dofmaps (for a mixed element)
  virtual std::size_t num_sub_dofmaps() const
  {
    return 0;
  }

  /// Create a new dofmap for sub dofmap i (for a mixed element)
  virtual ufc::dofmap* create_sub_dofmap(std::size_t i) const
  {
    return 0;
  }

  /// Create a new class instance
  virtual ufc::dofmap* create() const
  {
    return new ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_dofmap_0();
  }

};

/// This class defines the interface for the tabulation of the cell
/// tensor corresponding to the local contribution to a form from
/// the integral over a cell.

class ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_cell_integral_0_otherwise: public ufc::cell_integral
{
public:

  /// Constructor
  ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_cell_integral_0_otherwise() : ufc::cell_integral()
  {
    // Do nothing
  }

  /// Destructor
  virtual ~ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_cell_integral_0_otherwise()
  {
    // Do nothing
  }

  /// Tabulate which form coefficients are used by this integral
  virtual const std::vector<bool> & enabled_coefficients() const
  {
    static const std::vector<bool> enabled({});
    return enabled;
  }

  /// Tabulate the tensor for the contribution from a local cell
  virtual void tabulate_tensor(double*  A,
                               const double * const *  w,
                               const double*  vertex_coordinates,
                               int cell_orientation) const
  {
    // Number of operations (multiply-add pairs) for Jacobian data:      3
    // Number of operations (multiply-add pairs) for geometry tensor:    36
    // Number of operations (multiply-add pairs) for tensor contraction: 288
    // Total number of operations (multiply-add pairs):                  327
    
    // Compute Jacobian
    double J[4];
    compute_jacobian_triangle_2d(J, vertex_coordinates);
    
    // Compute Jacobian inverse and determinant
    double K[4];
    double detJ;
    compute_jacobian_inverse_triangle_2d(K, detJ, J);
    
    // Set scale factor
    const double det = std::abs(detJ);
    
    // Compute geometry tensor
    const double G0_0 = det*K[0]*(1.0);
    const double G0_1 = det*K[2]*(1.0);
    const double G1_0_0 = det*K[0]*K[0]*(1.0);
    const double G1_0_1 = det*K[0]*K[2]*(1.0);
    const double G1_1_0 = det*K[2]*K[0]*(1.0);
    const double G1_1_1 = det*K[2]*K[2]*(1.0);
    const double G2_0_0_0 = det*(K[0]*((K[0]*K[0] + K[1]*K[1])));
    const double G2_0_0_1 = det*(K[0]*((K[0]*K[2] + K[1]*K[3])));
    const double G2_0_1_0 = det*(K[0]*((K[2]*K[0] + K[3]*K[1])));
    const double G2_0_1_1 = det*(K[0]*((K[2]*K[2] + K[3]*K[3])));
    const double G2_1_0_0 = det*(K[2]*((K[0]*K[0] + K[1]*K[1])));
    const double G2_1_0_1 = det*(K[2]*((K[0]*K[2] + K[1]*K[3])));
    const double G2_1_1_0 = det*(K[2]*((K[2]*K[0] + K[3]*K[1])));
    const double G2_1_1_1 = det*(K[2]*((K[2]*K[2] + K[3]*K[3])));
    const double G3_0_0 = det*(K[0]*K[0] + K[1]*K[1]);
    const double G3_0_1 = det*(K[0]*K[2] + K[1]*K[3]);
    const double G3_1_0 = det*(K[2]*K[0] + K[3]*K[1]);
    const double G3_1_1 = det*(K[2]*K[2] + K[3]*K[3]);
    
    // Compute element tensor
    A[0] = -0.0666666666666665*G0_0 - 0.0666666666666665*G0_1 + 0.25*G1_0_0 + 0.25*G1_0_1 + 0.25*G1_1_0 + 0.25*G1_1_1 - 0.333333333333332*G2_0_0_0 - 0.333333333333338*G2_0_0_1 - 0.333333333333333*G2_0_1_0 - 0.333333333333338*G2_0_1_1 - 0.333333333333333*G2_1_0_0 - 0.333333333333338*G2_1_0_1 - 0.333333333333332*G2_1_1_0 - 0.333333333333338*G2_1_1_1 + 0.5*G3_0_0 + 0.5*G3_0_1 + 0.5*G3_1_0 + 0.5*G3_1_1;
    A[1] = -0.0333333333333333*G0_0 + 0.0833333333333338*G1_0_0 + 0.0833333333333331*G1_0_1 + 0.333333333333332*G2_0_0_0 + 0.333333333333333*G2_0_1_0 + 0.333333333333333*G2_1_0_0 + 0.333333333333332*G2_1_1_0 + 0.166666666666668*G3_0_0 + 0.166666666666666*G3_1_0;
    A[2] = -0.0333333333333333*G0_1 + 0.083333333333333*G1_1_0 + 0.0833333333333327*G1_1_1 + 0.333333333333335*G2_0_0_1 + 0.333333333333335*G2_0_1_1 + 0.333333333333335*G2_1_0_1 + 0.333333333333335*G2_1_1_1 + 0.166666666666666*G3_0_1 + 0.166666666666665*G3_1_1;
    A[3] = -0.0333333333333332*G0_0 - 0.0333333333333332*G0_1 + 1.33333333333333*G2_0_0_0 + 1.33333333333332*G2_0_0_1 + 1.33333333333333*G2_0_1_0 + 1.33333333333332*G2_0_1_1 + 1.33333333333333*G2_1_0_0 + 1.33333333333332*G2_1_0_1 + 1.33333333333333*G2_1_1_0 + 1.33333333333332*G2_1_1_1;
    A[4] = 0.0333333333333332*G0_0 + 0.1*G0_1 - 0.333333333333333*G1_1_0 - 0.333333333333333*G1_1_1 - 1.33333333333333*G2_0_0_0 - 1.33333333333333*G2_0_1_0 - 1.33333333333333*G2_1_0_0 - 1.33333333333333*G2_1_1_0 - 0.666666666666667*G3_0_1 - 0.666666666666667*G3_1_1;
    A[5] = 0.1*G0_0 + 0.0333333333333333*G0_1 - 0.333333333333334*G1_0_0 - 0.333333333333333*G1_0_1 - 1.33333333333333*G2_0_0_1 - 1.33333333333333*G2_0_1_1 - 1.33333333333333*G2_1_0_1 - 1.33333333333333*G2_1_1_1 - 0.666666666666667*G3_0_0 - 0.666666666666667*G3_1_0;
    A[6] = 0.0333333333333333*G0_0 + 0.0333333333333333*G0_1 + 0.0833333333333338*G1_0_0 + 0.0833333333333331*G1_1_0 - 0.333333333333332*G2_0_0_0 - 0.333333333333338*G2_0_0_1 + 0.166666666666668*G3_0_0 + 0.166666666666666*G3_0_1;
    A[7] = 0.0666666666666665*G0_0 + 0.25*G1_0_0 + 0.333333333333332*G2_0_0_0 + 0.5*G3_0_0;
    A[8] = -0.0333333333333333*G0_1 - 0.0833333333333332*G1_1_0 + 0.333333333333335*G2_0_0_1 - 0.166666666666666*G3_0_1;
    A[9] = -0.0333333333333333*G0_0 + 0.0666666666666664*G0_1 + 0.333333333333332*G1_1_0 + 1.33333333333333*G2_0_0_0 + 1.33333333333332*G2_0_0_1 + 0.666666666666663*G3_0_1;
    A[10] = 0.0333333333333333*G0_0 - 1.33333333333333*G2_0_0_0;
    A[11] = -0.1*G0_0 - 0.0666666666666665*G0_1 - 0.333333333333334*G1_0_0 - 0.333333333333333*G1_1_0 - 1.33333333333333*G2_0_0_1 - 0.666666666666667*G3_0_0 - 0.666666666666666*G3_0_1;
    A[12] = 0.0333333333333332*G0_0 + 0.0333333333333332*G0_1 + 0.0833333333333331*G1_0_1 + 0.0833333333333327*G1_1_1 - 0.333333333333333*G2_1_1_0 - 0.333333333333338*G2_1_1_1 + 0.166666666666666*G3_1_0 + 0.166666666666665*G3_1_1;
    A[13] = -0.0333333333333332*G0_0 - 0.0833333333333332*G1_0_1 + 0.333333333333332*G2_1_1_0 - 0.166666666666666*G3_1_0;
    A[14] = 0.0666666666666665*G0_1 + 0.25*G1_1_1 + 0.333333333333334*G2_1_1_1 + 0.5*G3_1_1;
    A[15] = 0.0666666666666664*G0_0 - 0.0333333333333334*G0_1 + 0.333333333333333*G1_0_1 + 1.33333333333333*G2_1_1_0 + 1.33333333333332*G2_1_1_1 + 0.666666666666666*G3_1_0;
    A[16] = -0.0666666666666664*G0_0 - 0.1*G0_1 - 0.333333333333333*G1_0_1 - 0.333333333333332*G1_1_1 - 1.33333333333333*G2_1_1_0 - 0.666666666666666*G3_1_0 - 0.666666666666665*G3_1_1;
    A[17] = 0.0333333333333333*G0_1 - 1.33333333333333*G2_1_1_1;
    A[18] = 0.0333333333333336*G0_0 + 0.0333333333333326*G0_1 - 0.333333333333332*G2_0_1_0 - 0.333333333333338*G2_0_1_1 - 0.333333333333332*G2_1_0_0 - 0.333333333333338*G2_1_0_1;
    A[19] = 0.1*G0_0 + 0.333333333333332*G1_0_1 + 0.333333333333332*G2_0_1_0 + 0.333333333333332*G2_1_0_0 + 0.666666666666663*G3_1_0;
    A[20] = 0.1*G0_1 + 0.333333333333333*G1_1_0 + 0.333333333333333*G2_0_1_1 + 0.333333333333333*G2_1_0_1 + 0.666666666666666*G3_0_1;
    A[21] = 0.266666666666666*G0_0 + 0.266666666666664*G0_1 + 0.666666666666664*G1_0_0 + 0.333333333333328*G1_0_1 + 0.333333333333328*G1_1_0 + 0.666666666666657*G1_1_1 + 1.33333333333333*G2_0_1_0 + 1.33333333333332*G2_0_1_1 + 1.33333333333333*G2_1_0_0 + 1.33333333333332*G2_1_0_1 + 1.33333333333333*G3_0_0 + 0.666666666666656*G3_0_1 + 0.666666666666656*G3_1_0 + 1.33333333333331*G3_1_1;
    A[22] = -0.266666666666666*G0_0 - 0.133333333333332*G0_1 - 0.666666666666664*G1_0_0 - 0.333333333333328*G1_0_1 - 0.333333333333329*G1_1_0 - 1.33333333333333*G2_0_1_0 + 1.03805852802452e-14*G2_0_1_1 - 1.33333333333333*G2_1_0_0 + 1.03805852802452e-14*G2_1_0_1 - 1.33333333333333*G3_0_0 - 0.666666666666659*G3_0_1 - 0.666666666666656*G3_1_0;
    A[23] = -0.133333333333334*G0_0 - 0.266666666666667*G0_1 - 0.333333333333333*G1_0_1 - 0.333333333333332*G1_1_0 - 0.666666666666662*G1_1_1 - 1.33333333333333*G2_0_1_1 - 1.33333333333333*G2_1_0_1 - 0.666666666666665*G3_0_1 - 0.666666666666666*G3_1_0 - 1.33333333333332*G3_1_1;
    A[24] = -0.1*G0_0 - 0.1*G0_1 - 0.333333333333333*G1_0_1 - 0.333333333333333*G1_1_1 + 0.333333333333332*G2_0_1_0 + 0.333333333333338*G2_0_1_1 + 0.333333333333332*G2_1_0_0 + 0.333333333333338*G2_1_0_1 + 0.666666666666665*G2_1_1_0 + 0.666666666666676*G2_1_1_1 - 0.666666666666667*G3_1_0 - 0.666666666666667*G3_1_1;
    A[25] = -0.0333333333333336*G0_0 - 0.333333333333332*G2_0_1_0 - 0.333333333333332*G2_1_0_0 - 0.666666666666665*G2_1_1_0 - 1.48214773787458e-14*G2_1_1_1;
    A[26] = 0.1*G0_1 - 0.333333333333333*G1_1_0 - 0.333333333333332*G1_1_1 - 0.333333333333333*G2_0_1_1 - 0.333333333333333*G2_1_0_1 - 0.666666666666668*G2_1_1_1 - 0.666666666666666*G3_0_1 - 0.666666666666665*G3_1_1;
    A[27] = 0.266666666666666*G0_0 + 0.133333333333331*G0_1 - 0.666666666666664*G1_0_0 - 0.333333333333329*G1_0_1 - 0.333333333333328*G1_1_0 - 1.33333333333333*G2_0_1_0 - 1.33333333333332*G2_0_1_1 - 1.33333333333333*G2_1_0_0 - 1.33333333333332*G2_1_0_1 - 2.66666666666666*G2_1_1_0 - 2.66666666666664*G2_1_1_1 - 1.33333333333333*G3_0_0 - 0.666666666666656*G3_0_1 - 0.666666666666659*G3_1_0;
    A[28] = -0.266666666666666*G0_0 + 0.666666666666664*G1_0_0 + 0.333333333333329*G1_0_1 + 0.333333333333329*G1_1_0 + 0.666666666666666*G1_1_1 + 1.33333333333333*G2_0_1_0 - 1.03805852802452e-14*G2_0_1_1 + 1.33333333333333*G2_1_0_0 - 1.03805852802452e-14*G2_1_0_1 + 2.66666666666666*G2_1_1_0 - 2.00950367457153e-14*G2_1_1_1 + 1.33333333333333*G3_0_0 + 0.666666666666659*G3_0_1 + 0.666666666666659*G3_1_0 + 1.33333333333333*G3_1_1;
    A[29] = 0.133333333333334*G0_0 - 0.133333333333333*G0_1 + 0.333333333333333*G1_0_1 + 0.333333333333332*G1_1_0 + 1.33333333333333*G2_0_1_1 + 1.33333333333333*G2_1_0_1 + 2.66666666666666*G2_1_1_1 + 0.666666666666665*G3_0_1 + 0.666666666666665*G3_1_0;
    A[30] = -0.1*G0_0 - 0.1*G0_1 - 0.333333333333334*G1_0_0 - 0.333333333333333*G1_1_0 + 0.666666666666664*G2_0_0_0 + 0.666666666666675*G2_0_0_1 + 0.333333333333333*G2_0_1_0 + 0.333333333333339*G2_0_1_1 + 0.333333333333333*G2_1_0_0 + 0.333333333333339*G2_1_0_1 - 0.666666666666667*G3_0_0 - 0.666666666666667*G3_0_1;
    A[31] = 0.1*G0_0 - 0.333333333333334*G1_0_0 - 0.333333333333333*G1_0_1 - 0.666666666666665*G2_0_0_0 - 1.48214773787458e-14*G2_0_0_1 - 0.333333333333334*G2_0_1_0 - 0.333333333333334*G2_1_0_0 - 0.666666666666667*G3_0_0 - 0.666666666666666*G3_1_0;
    A[32] = -0.0333333333333333*G0_1 - 0.666666666666669*G2_0_0_1 - 0.333333333333335*G2_0_1_1 - 0.333333333333335*G2_1_0_1;
    A[33] = 0.133333333333333*G0_0 + 0.266666666666664*G0_1 - 0.333333333333332*G1_0_1 - 0.333333333333333*G1_1_0 - 0.666666666666662*G1_1_1 - 2.66666666666666*G2_0_0_0 - 2.66666666666664*G2_0_0_1 - 1.33333333333333*G2_0_1_0 - 1.33333333333332*G2_0_1_1 - 1.33333333333333*G2_1_0_0 - 1.33333333333332*G2_1_0_1 - 0.666666666666666*G3_0_1 - 0.666666666666665*G3_1_0 - 1.33333333333332*G3_1_1;
    A[34] = -0.133333333333333*G0_0 + 0.133333333333335*G0_1 + 0.333333333333332*G1_0_1 + 0.333333333333333*G1_1_0 + 2.66666666666666*G2_0_0_0 - 1.7874590696465e-14*G2_0_0_1 + 1.33333333333333*G2_0_1_0 - 1.02140518265514e-14*G2_0_1_1 + 1.33333333333333*G2_1_0_0 - 1.02140518265514e-14*G2_1_0_1 + 0.666666666666665*G3_0_1 + 0.666666666666665*G3_1_0;
    A[35] = -0.266666666666667*G0_1 + 0.666666666666667*G1_0_0 + 0.333333333333334*G1_0_1 + 0.333333333333334*G1_1_0 + 0.666666666666667*G1_1_1 + 2.66666666666667*G2_0_0_1 + 1.33333333333334*G2_0_1_1 + 1.33333333333334*G2_1_0_1 + 1.33333333333333*G3_0_0 + 0.666666666666667*G3_0_1 + 0.666666666666667*G3_1_0 + 1.33333333333333*G3_1_1;
  }

};

/// This class defines the interface for the assembly of the global
/// tensor corresponding to a form with r + n arguments, that is, a
/// mapping
///
///     a : V1 x V2 x ... Vr x W1 x W2 x ... x Wn -> R
///
/// with arguments v1, v2, ..., vr, w1, w2, ..., wn. The rank r
/// global tensor A is defined by
///
///     A = a(V1, V2, ..., Vr, w1, w2, ..., wn),
///
/// where each argument Vj represents the application to the
/// sequence of basis functions of Vj and w1, w2, ..., wn are given
/// fixed functions (coefficients).

class ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_form_0: public ufc::form
{
public:

  /// Constructor
  ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_form_0() : ufc::form()
  {
    // Do nothing
  }

  /// Destructor
  virtual ~ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_form_0()
  {
    // Do nothing
  }

  /// Return a string identifying the form
  virtual const char* signature() const
  {
    return "62240747bf0e1f2a4eeb9ce8befbf15f066b03ab6e598e351e18957378f62e819547c8ee4b0201cf8ea09471608cd62e6a30db01af7b9d3ef91dc7cdc2013492";
  }


  /// Return the rank of the global tensor (r)
  virtual std::size_t rank() const
  {
    return 2;
  }

  /// Return the number of coefficients (n)
  virtual std::size_t num_coefficients() const
  {
    return 0;
  }

  /// Return original coefficient position for each coefficient (0 <= i < n)
  virtual std::size_t original_coefficient_position(std::size_t i) const
  {
    static const std::vector<std::size_t> position({});
    return position[i];
  }


  /// Create a new finite element for argument function i
  virtual ufc::finite_element* create_finite_element(std::size_t i) const
  {
    switch (i)
    {
    case 0:
      {
        return new ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_finite_element_0();
        break;
      }
    case 1:
      {
        return new ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_finite_element_0();
        break;
      }
    }
    
    return 0;
  }

  /// Create a new dofmap for argument function i
  virtual ufc::dofmap* create_dofmap(std::size_t i) const
  {
    switch (i)
    {
    case 0:
      {
        return new ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_dofmap_0();
        break;
      }
    case 1:
      {
        return new ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_dofmap_0();
        break;
      }
    }
    
    return 0;
  }


  /// Return the number of cell domains
  virtual std::size_t max_cell_subdomain_id() const
  {
    return 0;
  }

  /// Return the number of exterior facet domains
  virtual std::size_t max_exterior_facet_subdomain_id() const
  {
    return 0;
  }

  /// Return the number of interior facet domains
  virtual std::size_t max_interior_facet_subdomain_id() const
  {
    return 0;
  }

  /// Return the number of vertex domains
  virtual std::size_t max_vertex_subdomain_id() const
  {
    return 0;
  }

  /// Return the number of custom domains
  virtual std::size_t max_custom_subdomain_id() const
  {
    return 0;
  }


  /// Return whether the form has any cell integrals
  virtual bool has_cell_integrals() const
  {
    return true;
  }

  /// Return whether the form has any exterior facet integrals
  virtual bool has_exterior_facet_integrals() const
  {
    return false;
  }

  /// Return whether the form has any interior facet integrals
  virtual bool has_interior_facet_integrals() const
  {
    return false;
  }

  /// Return whether the form has any vertex integrals
  virtual bool has_vertex_integrals() const
  {
    return false;
  }

  /// Return whether the form has any custom integrals
  virtual bool has_custom_integrals() const
  {
    return false;
  }


  /// Create a new cell integral on sub domain subdomain_id
  virtual ufc::cell_integral* create_cell_integral(std::size_t subdomain_id) const
  {
    return 0;
  }

  /// Create a new exterior facet integral on sub domain subdomain_id
  virtual ufc::exterior_facet_integral* create_exterior_facet_integral(std::size_t subdomain_id) const
  {
    return 0;
  }

  /// Create a new interior facet integral on sub domain subdomain_id
  virtual ufc::interior_facet_integral* create_interior_facet_integral(std::size_t subdomain_id) const
  {
    return 0;
  }

  /// Create a new vertex integral on sub domain subdomain_id
  virtual ufc::vertex_integral* create_vertex_integral(std::size_t subdomain_id) const
  {
    return 0;
  }

  /// Create a new custom integral on sub domain subdomain_id
  virtual ufc::custom_integral* create_custom_integral(std::size_t subdomain_id) const
  {
    return 0;
  }


  /// Create a new cell integral on everywhere else
  virtual ufc::cell_integral* create_default_cell_integral() const
  {
    return new ffc_form_18f96071af3b89ab94a8a484efbd06f319830499_cell_integral_0_otherwise();
  }

  /// Create a new exterior facet integral on everywhere else
  virtual ufc::exterior_facet_integral* create_default_exterior_facet_integral() const
  {
    return 0;
  }

  /// Create a new interior facet integral on everywhere else
  virtual ufc::interior_facet_integral* create_default_interior_facet_integral() const
  {
    return 0;
  }

  /// Create a new vertex integral on everywhere else
  virtual ufc::vertex_integral* create_default_vertex_integral() const
  {
    return 0;
  }

  /// Create a new custom integral on everywhere else
  virtual ufc::custom_integral* create_default_custom_integral() const
  {
    return 0;
  }

};

#endif
